### ISSUE TITLE
Reset doesn't actually reset properties to original values

### ISSUE THREAD

**Issue by iros** [pbeshai/d3-scale-interactive#23]
I am assuming the intention is that they reset to the values that the panels started with?

**Comment by pbeshai** [comment]
If you can reproduce the bug of this not working, that'd be great! I just noticed once there were a number of errors in the console, but I refreshed and I'm not able to reproduce currently.

**Comment by iros** [comment]
Sure. From a fresh reload:

Change the 2nd domain value from it's original value

![image](https://cloud.githubusercontent.com/assets/18690/17842826/d34975ce-67f4-11e6-9bf2-0e3716f40ce0.png)

to another value (my particular example below.)

![image](https://cloud.githubusercontent.com/assets/18690/17842829/dcce8134-67f4-11e6-88d1-469db58a2f9e.png)

tab out of that field (change is visible in the chart.)

Now try to hit "Reset" to return to the original domain value but you won't (from what  I can tell.)

Does that work for you?
